apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  generation: 1
  name: frontend
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              number: 80
        path: /
        pathType: Prefix